objectives/urls.py
from django.urls import path,include

from . import views

app_name = 'objectives'
urlpatterns = [
    path('', views.display_index, name='index'),
    path('display_date', views.display_date_data, name='display_date'),
    path('master', views.NumberObjectiveMasterListView.as_view(), name='master_list'),
    path('master/create', views.NumberObjectiveMasterCreateView.as_view(), name='master_create'),
    path('master/update/<int:pk>', views.NumberObjectiveMasterUpdateView.as_view(), name='master_update'),
    path('week_objective/create/<str:datestr>', views.display_week_objective_form, name='week_objective_create'),
    path('week_objective/edit/<str:datestr>', views.display_week_objective_form_edit, name='week_objective_edit'),
    path('objrev/<str:key>/<str:target_date>', views.display_objrev_form, name='objrev_create'),

    # ajax
    path('ajax/freeword/register', views.ajax_freeword_register, name='ajax_freeword_register'),
    path('ajax/freeword/get', views.ajax_freeword_get, name='ajax_freeword_get'),
    path('ajax/weekobj/create', views.ajax_weekobj_create, name="ajax_weekobj_create"),
    path('ajax/dateOutput/create', views.ajax_dateoutput_create, name="ajax_dateoutput_create"),
    path('ajax/orderupd', views.ajax_numobjmst_order_update, name="ajax_numobjmst_update"),
]

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include

urlpatterns = [
    path('objectives/', include('objectives.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

objectives/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

# 数値種別
NUMBER_KIND_CHOICES = [
    ('N', '数値'),
    ('P', '時間'),
    ('T', '時刻'),
]

# 集計種別
SUMMARY_KIND = [
    ('S', '合計'),
    ('A', '平均'),
]

class User(AbstractUser):
    '''カスタムユーザー
    '''
    pass

class FreeInput(models.Model):
    '''自由入力：年・月・週・日の目標、振り返りの入力内容
    ・入力単位：Y/M/W/D
    ・入力種別：O(Objective)/R(Review)
    ・年：何年の記録か
    ・日番号：年・月・週・日の番号を入れる(週番号はisocalendar)
    ・フリーワード
    ・入力状況：入力済(1)/スキップ(2)…未入力はレコード無しで表現
    '''
    input_unit = models.CharField(
        max_length=1,
    )
    input_kind = models.CharField(
        max_length=1,
    )
    year = models.PositiveSmallIntegerField()
    day_index = models.PositiveSmallIntegerField()
    free_word = models.TextField(
        blank=True,
        null=True,
    )
    input_status = models.CharField(
        max_length=1,
        blank=True,
        null=True,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

class NumberObjectiveMaster(models.Model):
    '''数値目標マスタ：数値目標のマスタ
    ・名称
    ・数値種別：数値(N:Number)、時間(P:Period)、時刻(T:Time)
    ・集計種別：合計(S)、平均(A)
    ・有効フラグ：有効なもの：1、無効なもの：0(無効なものは週目標作成時には対象外になるが過去の実績は生かす)
    ・ユーザーID
    ・ソート順
    '''
    name = models.CharField(
        max_length=100,
        verbose_name='名称'
    )
    number_kind = models.CharField(
        max_length=1,
        choices=NUMBER_KIND_CHOICES,
        verbose_name='数値種別',
    )
    summary_kind = models.CharField(
        max_length=1,
        choices=SUMMARY_KIND,
        verbose_name='集計種別',
    )
    valid_flag = models.CharField(
        max_length=1,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    order_index = models.PositiveSmallIntegerField(
        verbose_name='表示順',
    )

class NumberObjective(models.Model):
    '''数値目標：週単位での数値目標の値を設定
    ・数値目標マスタID
    ・年(isoclendar)
    ・週番号
    ・目標値：時間の場合は分単位で記録、時刻の場合は00:00基準で分を記録
    ・目標達成フラグ：集計種別が「合計」で目標達成した場合、トップで目標達成メッセージを表示したあとフラグを立てる
    ・連続達成カウント：連続して目標達成した回数
    ・実績アップフラグ：集計種別が「合計」で前週の実績を超えた場合、トップでメッセージを表示したあとフラグを立てる
    ・実績アップカウント：連続して実績アップした回数
    '''
    master = models.ForeignKey(
        NumberObjectiveMaster,
        on_delete=models.CASCADE,
    )
    iso_year = models.PositiveSmallIntegerField()
    week_index = models.PositiveSmallIntegerField()
    objective_value = models.PositiveIntegerField()
    achieve_flg = models.CharField(
        max_length=1,
        default="0",
    )
    consecutive_count = models.PositiveSmallIntegerField(
        default=0,
    )
    exceed_flg = models.CharField(
        max_length=1,
        default="0",
    )
    exceed_consecutive_count = models.PositiveSmallIntegerField(
        default=0,
    )

class NumberObjectiveOutput(models.Model):
    '''数値目標実績：日毎の数値目標実績を登録
    ・数値目標マスタID
    ・年
    ・月
    ・年(isocalendar)：週での集計時に使用
    ・週番号
    ・日付番号：日付の番号
    ・実績値：時間の場合は分単位で記録、時刻の場合は00:00基準で分を記録
    '''
    master = models.ForeignKey(
        NumberObjectiveMaster,
        on_delete=models.CASCADE,
    )
    year = models.PositiveSmallIntegerField()
    month = models.PositiveSmallIntegerField()
    iso_year = models.PositiveSmallIntegerField()
    week_index = models.PositiveSmallIntegerField()
    date_index = models.PositiveSmallIntegerField()
    day_of_week = models.PositiveSmallIntegerField()
    output_value = models.PositiveIntegerField()

objectives/forms.py
from django import forms
from .models import NumberObjectiveMaster


class NumberObjectiveMasterForm(forms.ModelForm):
    '''数値目標マスターフォーム'''
    class Meta:
        model = NumberObjectiveMaster
        fields = ('name', 'number_kind', 'summary_kind',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

objectives/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Max, Sum

from datetime import datetime,date,timedelta

from .forms import NumberObjectiveMasterForm
from .models import *

# Create your views here.

class NumberObjectiveMasterListView(LoginRequiredMixin, ListView):
    '''数値目標一覧画面'''
    template_name = "numberobjectivemaster/list.html"
    model = NumberObjectiveMaster

    def get_queryset(self):
        return NumberObjectiveMaster.objects.filter(user=self.request.user).order_by('order_index')

class NumberObjectiveMasterCreateView(LoginRequiredMixin, CreateView):
    '''数値目標マスタ作成画面'''
    template_name = "numberobjectivemaster/create.html"
    form_class = NumberObjectiveMasterForm
    success_url = reverse_lazy('objectives:master_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.valid_flag = "1"
        # ソート順は登録済みレコードのmax+1を登録する
        max = NumberObjectiveMaster.objects.filter(
            user=self.request.user,
            valid_flag="1",
            ).aggregate(Max("order_index"))
        form.instance.order_index = max["order_index__max"]+1
        return super().form_valid(form)

class NumberObjectiveMasterUpdateView(LoginRequiredMixin, UpdateView):
    '''数値目標マスタ更新画面'''
    model = NumberObjectiveMaster
    template_name = "numberobjectivemaster/create.html"
    form_class = NumberObjectiveMasterForm
    success_url = reverse_lazy('objectives:master_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.valid_flag = "1"
        return super().form_valid(form)

@login_required
def display_index(request):
    today = date.today().strftime("%Y-%m-%d")
    # 今日日付でデータ取得
    dateFreeObjective, dateFreeReview, weekFreeObjective, numberObjective, objRevFlgList = get_date_data(request, today)

    return render(request, 'objectives/index.html', {
        'display_date': today,
        'dateFreeObjective': dateFreeObjective,
        'dateFreeReview': dateFreeReview,
        'weekFreeObjective': weekFreeObjective,
        'numberObjective': numberObjective,
        'objRevFlgList': objRevFlgList,
        })

@login_required
def display_date_data(request):
    # 指定された日付でデータ取得
    display_date = request.GET.get('target_date')
    return display_date_data_from_view(request, display_date)

def display_date_data_from_view(request, target_date):
    '''templateからではなくviewでtarget_date指定してindex表示する'''
    dateFreeObjective, dateFreeReview, weekFreeObjective, numberObjective, objRevFlgList = get_date_data(request, target_date)
    return render(request, 'objectives/index.html', {
        'display_date': target_date,
        'dateFreeObjective': dateFreeObjective,
        'dateFreeReview': dateFreeReview,
        'weekFreeObjective': weekFreeObjective,
        'numberObjective': numberObjective,
        'objRevFlgList': objRevFlgList,
        })

@login_required
def get_date_data(request, display_date):
    '''以下のデータを取得
    ・指定された日付の以下データ
    　・フリーワード(目標・振り返り)
    　・指定された日付の数値目標、実績値
    　⇒数値目標は指定された日付の週に目標として設定されたものを表示
    　・指定された日付の週のフリーワード(目標)
    　・年、月の目標設定有無
    　・前年、前月、前週の振り返り有無(目標が設定されている場合のみ)
    '''
    # 返却する値の初期化
    year, month, date_index, week_tuple = get_date(display_date)
    
    # 数値目標取得：achieve_item,exceed_itemは使わない
    numberObjective, achieve_item, exceed_item = getNumObj(request.user, date_index, week_tuple)

    # 自由入力の取得
    dateFreeObjective = get_free_input_date(year, date_index, "O", request.user).first()
    dateFreeReview = get_free_input_date(year, date_index, "R", request.user).first()
    weekFreeObjective = get_free_input_week(week_tuple[0], week_tuple[1], "O", request.user).first()
    # 前年、前月取得
    pYear = str(int(year) - 1)
    (pMYear, pMonth) = (year, str(int(month) - 1)) if int(month) > 1 else (str(int(year) - 1), "12")
    # 前週の変数取得
    pWYear, pWMonth, pWDate_index, pWWeek_tuple = get_date(get_date_str_diff(display_date, -7))
    # 前日の変数取得
    pDYear, pDMonth, pDDate_index, pDWeek_tuple = get_date(get_date_str_diff(display_date, -1))

    # 年・月の目標設定有無(有：1、無：0)
    # 年・月・週・日の振り返り設定有無(目標設定有&振り返り設定無：0、それ以外：1)
    objRevFlgList = {
        'TYO': '1' if get_free_input_year(year, "O", request.user) else '0',
        'TMO': '1' if get_free_input_month(year, month, "O", request.user) else '0',
        'TYR': '1' if get_free_input_year(year, "R", request.user) else '0',
        'TMR': '1' if get_free_input_month(year, month, "R", request.user) else '0',
        'TWR': '1' if get_free_input_week(week_tuple[0], week_tuple[1], "R", request.user) else '0',
        # 使わない項目は0渡す
        'PYR': '0' if (get_free_input_year(pYear, "O", request.user)
                and not get_free_input_year(pYear, "R", request.user)) else '1',
        'PMR': '0' if (get_free_input_month(pMYear, pMonth, "O", request.user)
                and not get_free_input_month(pMYear, pMonth, "R", request.user)) else '1',
        'PWR': '0' if (get_free_input_week(pWWeek_tuple[0], pWWeek_tuple[1], "O", request.user)
                and not get_free_input_week(pWWeek_tuple[0], pWWeek_tuple[1], "R", request.user)) else '1',
        'PDR': '0' if (get_free_input_date(pDYear, pDDate_index, "O", request.user)
                and not get_free_input_date(pDYear, pDDate_index, "R", request.user)) else '1',
    }
    return dateFreeObjective, dateFreeReview, weekFreeObjective, numberObjective, objRevFlgList

@login_required
def ajax_freeword_register(request):
    '''ajaxで送信されたパラメータを元にFreeInputを登録する。
    '''
    print("*****[#ajax_freeword_register]start*****")
    free_word = request.POST['free_word']
    year, month, date_index, week_tuple = get_date(request.POST['input_date'])
    # 日番号：年・月・週・日
    day_index_dic = {'Y':year,'M':month,'W':week_tuple[1],'D':date_index}
    input_unit = request.POST['input_unit']
    input_kind = request.POST['input_kind']
    # 年：isocalendarは第１木曜の含まれる週を第１週とする週単位となるため、年が実際の年と異なる場合アリ
    register_year = week_tuple[0] if input_unit=='W' else year

    msg_str_unit = {'Y':'年','M':'月','W':'週','D':'日'}
    msg_str_kind = {'O':'目標','R':'振返り'}
    msg=msg_str_unit[input_unit]+'の'+msg_str_kind[input_kind]+'を'

    freeInput = FreeInput.objects.filter(
        input_unit = input_unit,
        input_kind = input_kind,
        year = register_year,
        day_index = day_index_dic[input_unit],
        user = request.user,
    ).first()
    if freeInput is None:
        freeInput = FreeInput(
            input_unit = input_unit,
            input_kind = input_kind,
            year = register_year,
            day_index = day_index_dic[input_unit],
            free_word = free_word,
            input_status = 1,
            user = request.user,
        )
        msg+="登録しました！"
    else:
        freeInput.free_word = free_word
        msg+="更新しました！"
    freeInput.save()

    # TODO エラーハンドリング
    return HttpResponse(msg)

@login_required
def ajax_freeword_get(request):
    '''ajaxで送信されたパラメータを元にFreeInputを取得しJsonで返却する。
    '''
    print("*****[#ajax_freeword_get]start*****")
    input_unit = request.GET['input_unit']
    input_kind = request.GET['input_kind']
    user_id = request.GET['user']
    user = User.objects.get(id=user_id)
    year, month, date_index, week_tuple = get_date(request.GET['input_date'])
    freeInput = get_free_input(input_unit, input_kind, year, month, date_index, week_tuple, user)
    json = serializers.serialize('json', freeInput, ensure_ascii=False)
    return HttpResponse(json, content_type='application/json; charset=UTF-8')

@login_required
def ajax_weekobj_create(request):
    '''ajaxで送信されたデータを元に週目標を登録する'''
    print("*****[#ajax_weekobj_create]start*****")
    data = json.loads(request.body)
    print(data)
    target_date = data["target_date"]
    if (target_date != ''):
        free_word = data["free_word"]
        year, month, date_index, week_tuple = get_date(target_date)
        print(free_word)
        if (free_word != ''):
            freeInput = get_free_input_week(week_tuple[0], week_tuple[1], "O", request.user).first()
            # 新規作成
            if data["mode"] == "C":
                # 二重登録防止
                if freeInput is None:
                    freeInput = FreeInput(
                        input_unit = 'W',
                        input_kind = 'O',
                        year = week_tuple[0],
                        day_index = week_tuple[1],
                        free_word = free_word,
                        input_status = 1,
                        user = request.user,
                    )
                    freeInput.save()
            # 更新
            else:
                freeInput.free_word = free_word
                freeInput.save()
        objectives = data["objectives"]
        print(objectives)
        # 新規作成
        if data["mode"] == "C":
            for obj in objectives:
                numberObjective = NumberObjective(
                    master = NumberObjectiveMaster.objects.get(id=int(obj["master_id"])),
                    iso_year = week_tuple[0],
                    week_index = week_tuple[1],
                    objective_value = int(obj["value"]),
                )
                numberObjective.save()
        # 更新
        else:
            # 数値目標マスタを全件取得の上、登録値あり＆入力値あり：更新、登録値あり＆入力値なし：削除
            # 登録値なし＆入力値あり：登録、登録値なし＆入力値なし：なにもしない
            master = NumberObjectiveMaster.objects.filter(
                valid_flag = "1",
                user = request.user,
            )
            for m in master:
                # 数値目標登録値の有無確認
                numberObjective = NumberObjective.objects.filter(

templates/objectives/objrev_form.html
{% extends "_base.html" %}
{% block content %}
{% load get_dic_vals %}
<script type="text/javascript">
    // グラフを毎回初期化するためグローバル変数化
    var chart;
    $(function () {
        if ("{{input_kind}}" == "R") {
            // 振返りの場合、目標入力欄を読み取り専用に
            $(".obj").attr("readOnly", true);
        }
        // 入力値を投げる
        $("#obj_rev_submit").on("click", function(e){
            e.preventDefault();
            var date = "{{ target_date_str }}";
            var path = location.pathname;
            var key = path.split("/")[3];
            var input_unit = key.substring(1,2);
            var input_kind = key.substring(2,3);
            var id = input_kind == "R" ? "{{ free_input_rev.id }}" : "{{ free_input.obj.id }}";
            var free_word = input_kind == "R" ? $(".rev").val().trim() : $(".obj").val().trim();
            if (free_word == "") {
                $("#invalid-fb").text("入力してください。");
            }
            
            // 処理前に Loading 画像を表示
            dispLoading("処理中...");

            // 年、月の場合、月、日を補完する
            if (input_unit == "Y") {
                date += "-01-01";
            } else if (input_unit == "M") {
                date += "-01";
            }
            var url = "{% url 'objectives:ajax_freeword_register' %}";
            var token = "{{csrf_token}}";
            $.ajax({
                url: url,
                method: "POST",
                headers: { "X-CSRFToken": token },
                data: {
                    "id": id,
                    "input_unit": input_unit,
                    "input_kind": input_kind,
                    "free_word": free_word,
                    "input_date": date 
                },
                timeout: 10000,
                datatype: "text",
            })
            .then(
                function(msg){
                    swal({
                        title: msg,
                        icon: "success",
                        text: " ", // ダイアログのサイズ調整のためtext設定
                        buttons: false,
                    });
                    window.location.href = "{% url 'objectives:index' %}";
                },
                function(){
                    ajaxError();
                }
            )
            .always(function(){
                removeLoading();
            });
        });
        $(".obj_rev_tr").on("click", function(e){
            e.preventDefault();
            var cht = $("#obj_rev_chart");
            var labelsDOM = $(".obj_rev_head").children("th");
            var labels = [];
            var vals = [];
            var graphType = ""
            var itemName = $(this).children("th")[0].innerText;
            {% if input_unit == "W" %}
            const head_col = 3;
            {% else %}
            const head_col = 2;
            {% endif %}
            labelsDOM.each(function(idx, dom){
                if (idx > head_col-1) {
                    labels.push(dom.innerText);
                }
            })
            $(this).children("td").each(function(idx, dom){
                if (idx == 0) {
                    if (dom.innerText == "合計") {
                        graphType = "bar";
                    } else {
                        graphType = "line";
                    }
                }
                if (idx > head_col-1) {
                    var val = dom.innerText.split(" ")[0];
                    if (val.indexOf(":") > 0) {
                        val = val.split(":");
                        val = parseInt(val[0]) * 60 + parseInt(val[1]);
                    }
                    vals.push(val);
                }
            })
            if (chart) {
                chart.destroy();
            }
            chart = new Chart($(cht), {
                type: graphType,
                data: {
                    labels: labels,
                    datasets: [{
                        label: itemName,
                        data: vals,
                        backgroundColor: "rgba(255,99,132,0.2",
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            })
        })
    })
</script>
<h4>{{ input_unit|input_unit }}の{{ input_kind|input_kind }} ({{ target_period_str }})</h4>
<div id="invalid-fb"></div>
<div class="row">
    <!-- 自由入力 -->
    <div class="col-12">
        <div>目標</div>
        <div class="form-group objective-review-group">
            <textarea class='form-control obj' rows='6' data-toggle="tooltip"
                      title="{{ free_input_obj.free_word|default_if_none:'' }}">{{ free_input_obj.free_word|default_if_none:"" }}</textarea>
        </div>
    </div>
    {% if input_kind == "R" %}
    <div class="col-12">
        <div>振返り</div>
        <div class="form-group objective-review-group">
            <textarea class='form-control rev' rows='6' data-toggle="tooltip"
                      title="{{ free_input_rev.free_word|default_if_none:'' }}">{{ free_input_rev.free_word|default_if_none:"" }}</textarea>
        </div>
    </div>
    {% endif %}
</div>
<div class="row">
    <input id="obj_rev_submit" type="submit" class="btn btn-primary" value="登録"/>
</div>
<!-- 振り返りの場合、数値目標の実績集計値も表示 -->
{% if input_kind == "R" %}
<div class="row">
    <div class="table-responsive">
        <table class="table table-hover text-nowrap">
            <thead>
                <tr class="obj_rev_head">
                    <th colspan="2">数値目標</th>
                    {% if input_unit == "W" %}
                    <th>目標値</th>
                    {% endif %}
                    {% for hd in sum_header %}
                    <th>{{ hd }}</th>
                    {% endfor %}        
                </tr>
            </thead>
            <tbody>
                {% for obj in num_obj_rev %}
                <tr class="obj_rev_tr">
                    <th>
                        {{ obj.name }}
                    </th>
                    <td style="text-align: right">
                    {% if obj.summary_kind == 'S' %}
                        合計
                    {% elif obj.summary_kind == 'A' %}
                        平均
                    {% endif %}
                    </td>
                    <!--TODO-->
                    {% if obj.number_kind == 'N' %}
                        {% include "objectives/_objrev_number.html" %}
                    {% elif obj.number_kind == 'P' %}
                        {% include "objectives/_objrev_period.html" %}
                    {% elif obj.number_kind == 'T' %}
                        {% include "objectives/_objrev_time.html" %}     
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>            
    </div>
</div>
<canvas id="obj_rev_chart" style="width: 100%; height:300px;"></canvas>
{% endif %}
{% endblock %}

templates/objectives/week_objective_form.html
{% extends "_base.html" %}
{% block content %}
<script type="text/javascript">
    $(function(){
        // 入力値を投げる
        $(".wk_obj_submit").on("click", function(e){
            e.preventDefault();
            var path = location.pathname;
            var target_date = path.split("/")[4];
            var free_word = $(".objective-review-input").val().trim();
            var objectives = [];
            var rows = $(".wk_obj_row");
            rows.each(function(idx, row){
                var obj = {};
                // id
                var id = $(row).attr("id").split("_")[1];
                // 目標値
                var dom = $(row).find(".input_obj");
                var val = $(dom).val();
                var number_kind = $(dom).attr("id").split("_")[1];
                // 入力がある場合のみ登録
                if (val) {
                    if (number_kind != "N"){
                        // 時間の変換
                        val = parseInt(val.split(":")[0]) * 60 + parseInt(val.split(":")[1]) 
                    }
                    obj = {
                        "master_id": id,
                        "value": val
                    }
                    objectives.push(obj); 
                }
            });
            if (free_word == ""){
                $("#w_fi").addClass("is-invalid");
                $("#invalid-fb").text("入力してください。");
            } else if (objectives.length == 0){
                $("#w_fi").removeClass("is-invalid");
                $("#invalid-fb").text("");
                $(".msg-area").text("数値目標を最低1つ入力してください。");
            } else {
                // 処理前に Loading 画像を表示
                dispLoading("処理中...");
                var token = '{{csrf_token}}';
                $.ajax({
                    url: "{% url 'objectives:ajax_weekobj_create' %}",
                    method: "POST",
                    headers: { "X-CSRFToken": token },
                    dataType: "json",
                    data: JSON.stringify({
                        "target_date": target_date,
                        "free_word": free_word,
                        "objectives": objectives,
                        "mode": $(this).attr("id")
                    }),
                    timeout: 10000,
                })
                .then(
                    function(){
                        swal({
                            title: "週の目標を登録しました！",
                            icon: "success",
                            text: " ", // ダイアログのサイズ調整のためtext設定
                            buttons: false,
                        });
                    window.location.href = "/objectives/display_date?target_date=" + target_date;
                    },
                    function(){
                        ajaxError();
                    }
                )
                .always(function(){
                    removeLoading();
                });
            }
        })
    })
</script>
<h4>週の目標 ({{ start_date_str }} ~ {{ end_date_str }})</h4>
<div class="row">
    <!-- 自由入力 -->
    <div class="col-12">
        <div id="invalid-fb"></div>
        <div class="form-group objective-review-group">
            <textarea id="w_fi" class='form-control objective-review-input' rows='6'
                      data-toggle="tooltip"
                      title="{{ free_input.free_word|default_if_none:'' }}">{{ free_input.free_word|default_if_none:"" }}</textarea>
        </div>
    </div>
    <!-- 数値目標 -->
    <div class="col-12 msg-area"></div>
</div>
<div class="row">
    <div class="table-responsive">
        <table class="table table-hover text-nowrap">
            <thead>
                <tr class="obj_rev_head">
                    <th colspan="2">数値目標</th>
                    <th>目標値</th>
                    <th>前週実績</th> 
                </tr>
            </thead>
            <tbody>
            <!-- 数値目標マスタ件数分行を作る -->
            {% for master in masters %}
                <!-- 名称 -->
                <tr class="obj_rev_tr wk_obj_row" id="row_{{ master.id }}">
                    <th>
                        {{ master.name }}
                    </th>
                    <!-- 集計単位 -->
                    <td style="text-align: right">
                    {% if master.summary_kind == 'S' %}
                        週
                    {% elif master.summary_kind == 'A' %}
                        平均
                    {% endif %}
                    </td>
                    <!-- number_kind毎に形式分け -->
                    {% if master.number_kind == 'N' %}
                        {% include "objectives/_week_objective_number.html" %}
                    {% elif master.number_kind == 'P' %}
                        {% include "objectives/_week_objective_period.html" %}
                    {% elif master.number_kind == 'T' %}
                        {% include "objectives/_week_objective_time.html" %}     
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <input id="{{mode}}" type="submit" class="btn btn-primary wk_obj_submit" value="登録"/>
</div>
{% endblock %}