objectives/urls.py
from django.urls import path,include

from . import views

app_name = 'objectives'
urlpatterns = [
    path('', views.display_index, name='index'),
    path('display_date', views.display_date_data, name='display_date'),
    path('master', views.NumberObjectiveMasterListView.as_view(), name='master_list'),
    path('master/create', views.NumberObjectiveMasterCreateView.as_view(), name='master_create'),
    path('master/update/<int:pk>', views.NumberObjectiveMasterUpdateView.as_view(), name='master_update'),
    path('week_objective/create/<str:datestr>', views.display_week_objective_form, name='week_objective_create'),
    path('week_objective/edit/<str:datestr>', views.display_week_objective_form_edit, name='week_objective_edit'),
    path('objrev/<str:key>/<str:target_date>', views.display_objrev_form, name='objrev_create'),

    # ajax
    path('ajax/freeword/register', views.ajax_freeword_register, name='ajax_freeword_register'),
    path('ajax/freeword/get', views.ajax_freeword_get, name='ajax_freeword_get'),
    path('ajax/weekobj/create', views.ajax_weekobj_create, name="ajax_weekobj_create"),
    path('ajax/dateOutput/create', views.ajax_dateoutput_create, name="ajax_dateoutput_create"),
    path('ajax/orderupd', views.ajax_numobjmst_order_update, name="ajax_numobjmst_update"),
]

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include

urlpatterns = [
    path('objectives/', include('objectives.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/numberobjectivemaster/create.html
{% extends "_base.html" %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    {{form}}

    <input class="btn btn-primary" type="submit" value="登録"/>
</form>

{% endblock %}

templates/numberobjectivemaster/list.html
{% extends "_base.html" %}
{% load get_dic_vals %}
{% block content %}
<script type="text/javascript">
    $(function(){
        $("#numObjMstList").bind("sortstop", function(){
            // 処理前に Loading 画像を表示
            //dispLoading("処理中...");
            var arr = {};
            $(".num_obj_mst_list_row").each(function(i, d){
                arr[$(d).attr("id")] = i+1;
            })
            // 非同期でソート順更新
            $.ajax({
                url: "{% url 'objectives:ajax_numobjmst_update' %}",
                method: "POST",
                headers: { "X-CSRFToken": '{{csrf_token}}' },
                data: JSON.stringify({
                    "data": arr,
                    "user": {{ user.id }}
                }),
                timeout: 10000,
                datatype: "json",
            })
        })
    })
</script>
<a class="btn btn-dark" href="{% url 'objectives:master_create' %}">マスタ追加</a>
<table class="table table-hover">
    <thead>
        <tr>
            <th>名称</th>
            <th>数値種別</th>
            <th>集計種別</th>
        </tr>
    </thead>
    <tbody class="sortable" id="numObjMstList">
        {% for item in object_list %}
        <tr class="num_obj_mst_list_row" id="{{ item.id }}">
            <td><a href="{% url 'objectives:master_update' item.id %}">{{ item.name }}</a></td>
            <!-- TODO カスタムフィルタで辞書オブジェクトから値変換して区分値を表示させる -->
            <td>{{ item.number_kind|number_kind_choices }}</td>
            <td>{{ item.summary_kind|summary_kind }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">
                マスタがありません。
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}