objectives/urls.py
from django.urls import path,include

from . import views

app_name = 'objectives'
urlpatterns = [
    path('', views.display_index, name='index'),
    path('display_date', views.display_date_data, name='display_date'),
    path('master', views.NumberObjectiveMasterListView.as_view(), name='master_list'),
    path('master/create', views.NumberObjectiveMasterCreateView.as_view(), name='master_create'),
    path('master/update/<int:pk>', views.NumberObjectiveMasterUpdateView.as_view(), name='master_update'),
    path('week_objective/create/<str:datestr>', views.display_week_objective_form, name='week_objective_create'),
    path('week_objective/edit/<str:datestr>', views.display_week_objective_form_edit, name='week_objective_edit'),
    path('objrev/<str:key>/<str:target_date>', views.display_objrev_form, name='objrev_create'),

    # ajax
    path('ajax/freeword/register', views.ajax_freeword_register, name='ajax_freeword_register'),
    path('ajax/freeword/get', views.ajax_freeword_get, name='ajax_freeword_get'),
    path('ajax/weekobj/create', views.ajax_weekobj_create, name="ajax_weekobj_create"),
    path('ajax/dateOutput/create', views.ajax_dateoutput_create, name="ajax_dateoutput_create"),
    path('ajax/orderupd', views.ajax_numobjmst_order_update, name="ajax_numobjmst_update"),
]

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include

urlpatterns = [
    path('objectives/', include('objectives.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags always come first -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>mokuhyooo2</title>
    <!-- bootstrap css -->
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
    <!-- bootstrap4 datetimepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" />
    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha384-Dziy8F2VlJQLMShA6FHWNul/veM9bCkRUaLqr199K94ntO5QUrLJBEbYegdSkkqX" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js" integrity="sha384-fYxN7HsDOBRo1wT/NSZ0LkoNlcXvpDpFy6WzB42LxuKAX7sBwgo7vuins+E1HCaw" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/ja.js" integrity="sha384-oXDUAIMbbXBRmwoB+RqFKdyIHd5ny4sLABYrB/XrW8DcFdtns6K52DZRXvG8lpw1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha384-7+ImCvz/PDFsHevxN/SH5PaqmRRGpVl3dtDoKBFHhNQyKABEKLpbMj+rCsFdx0nF" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js" integrity="sha384-MI/QivrbkVVJ89UOOdqJK/w6TLx0MllO/LsQi9KvvJFuRHGbYtsBvbGSM8JHKCS0" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js" integrity="sha384-RIQuldGV8mnjGdob13cay/K1AJa+LR7VKHqSXrrB5DPGryn4pMUXRLh92Ev8KlGF" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js" integrity="sha384-Lp41XaGSjhdLPXSnc8/e6xAyddl0kRuBAggUJ/5HnDmEC1WaFPD5mBTAwlKfq0aB" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
<script type="text/javascript">
    $(function(){
        // 時刻・期間入力項目の入力制御(数値、コロンのみ)
        $("[with]").off(".inputcontrol")
        $("[with='time']")
            .off(".inputcontrol.time")
            .on("keyup.inputcontrol.time", function(){
                $(this).val($(this).val().replace(/[^0-9:]/g,""));
            })
        // 時刻・期間入力項目のフォーカスアウト時制御
        $(".input_pe, .input_ti").on("focusout", function(e){
            e.preventDefault();
            var str = $(this).val();
            var tmpInt = null;
            var numKind = ""; // 時間：P,時刻：T
            if ($(this).attr("class").indexOf("input_pe") != -1){
                numKind = "P"
            } else {
                numKind = "T"
            }
            var [outStr, errMsg] = timeFormat(str, numKind);
            $(".msg-area").text(errMsg);
            $(this).val(outStr);
        })
        $(".sortable").sortable({
            axis: "y",
        });
        $(".sortable").disableSelection(); 
        $("[data-toggle='tooltip']").tooltip();
    })
    // 時刻、時間をフォーマットして返す 
    timeFormat = function(str, numKind){
        var outStr = "";
        var msg = "";
        if (str != "") {
            // 1. コロン無しの場合、時:分に変換
            if (str.indexOf(":") == -1) {
                tmpInt = parseInt(str, 10);
                str = (tmpInt / 60 | 0).toString() + ":" + ('00' + (tmpInt % 60)).slice(-2);
            }
            var strArr = str.split(":");
            // 2. コロン前後のチェック
            if (strArr[1].length > 2) {
                msg = "xx:xxの形式で入力してください。"; // フォーマットエラー
            } else if (numKind == "P" && parseInt(strArr[0], 10) >= 24) {
                // 期間 & 時≧24
                msg = "期間は0:00~23:59の間で入力してください。"; // 期間オーバーエラー
            } else if (numKind == "T" && parseInt(strArr[0], 10) >= 48) {
                // 時刻 & 時≧48
                msg = "時刻は0:00~47:59の間で入力してください。"; // 時刻オーバーエラー
            }
            // 3. フォーマット
            if (msg == "") {
                if (strArr[0] == "") strArr[0] = "0";
                outStr = strArr[0] + ":" + ('00' + strArr[1]).slice(-2);
            }
        }
        return [outStr, msg];
    }
    // ajaxリクエストエラー時の処理
    function ajaxError() {
        swal({
            title: "登録に失敗しました",
            text: "時間をおいて再実行してください。",
            icon: "error",
        })
    }
    /* ------------------------------
    Loading イメージ表示関数
    引数： msg 画面に表示する文言
    ------------------------------ */
    function dispLoading(msg){
        // 引数なし（メッセージなし）を許容
        if( msg == undefined ){
        msg = "";
        }
        // 画面表示メッセージ
        var dispMsg = "<div class='loadingMsg'>" + msg + "</div>";
        // ローディング画像が表示されていない場合のみ出力
        if($("#loading").length == 0){
        $("body").append("<div id='loading'>" + dispMsg + "</div>");
        }
    }
    /* ------------------------------
    Loading イメージ削除関数
    ------------------------------ */
    function removeLoading(){
        $("#loading").remove();
    }
</script>
<div class="container-fruid">
    {% include './_base_nav.html' %}
    <div id="block-content" class="pad-top-56">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

templates/_base_nav.html
<nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="{% url 'objectives:index' %}">mokuhyooo2</a>
    {% if not user.is_anonymous %}
    <button type="button" class="navbar-toggler"
        data-toggle="collapse" data-target="#navbarNavDropdown" area-controls="navbarNavDropdown"
        aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto"></ul>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{user.get_username}}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="nav-link" href="{% url 'objectives:master_list' %}">数値目標マスタ</a>
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                    <a class="nav-link" href="#">withdraw</a>
                </div>
            </li>
        </ul>
    </div>
    {% endif %}
    <!-- /.navbar-collapse -->
</nav>